### ISSUE TITLE
If translate api key is missing, program will crash

### ISSUE THREAD

**Issue by yupm** [blueaxis/Poricom#56]
Choose ChatGPT or DeepL but leave api key missing. Program crashes after attempting translate

```
'TranslateOptions' object has no attribute 'apiLabel'
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: Unsupported ICC profile class 70727472
qt.gui.icc: Unsupported ICC profile class 70727472
Traceback (most recent call last):
  File "/home/yupm/anaconda3/envs/poricom-py39/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/yupm/anaconda3/envs/poricom-py39/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/yupm/anaconda3/envs/poricom-py39/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yupm/anaconda3/envs/poricom-py39/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yupm/Documents/Git/Poricom/app/services/workers/base.py", line 44, in run
    output = self.fn(*self.args, **self.kwargs)
  File "/home/yupm/Documents/Git/Poricom/app/services/states.py", line 241, in predictTranslate
    response = post(
  File "/home/yupm/anaconda3/envs/poricom-py39/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted (core dumped)
```

**Comment by blueaxis** [comment]
I remember encountering this error and fixing it. And the latest release seems to be working on my end.

I think I just forgot to commit/push the changes, will check this weekend
